sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t k8straining/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true k8straining/docker-react npm run test   -- --coverage